- name: Deploy Web Servers on Azure VMs
  hosts: webservers
  become: yes
  vars:
    web_port: 8080
  tasks:
    - name: Install Apache
      package:
        name: apache2
        state: present

    - name: Start and Enable Apache Service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Configure Apache to Listen on Port 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 8080'
      notify: Restart Apache

    - name: Create Web Page
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Hello World</title></head>
          <body>
          <h1>Hello World from SJSU-{{ '1' if inventory_hostname == 'vm1' else '2' }}</h1>
          </body>
          </html>

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

   
